<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ This file is part of StyleBI.
  ~ Copyright (C) 2024  InetSoft Technology
  ~
  ~ This program is free software: you can redistribute it and/or modify
  ~ it under the terms of the GNU Affero General Public License as published by
  ~ the Free Software Foundation, either version 3 of the License, or
  ~ (at your option) any later version.
  ~
  ~ This program is distributed in the hope that it will be useful,
  ~ but WITHOUT ANY WARRANTY; without even the implied warranty of
  ~ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  ~ GNU Affero General Public License for more details.
  ~
  ~ You should have received a copy of the GNU Affero General Public License
  ~ along with this program.  If not, see <https://www.gnu.org/licenses/>.
  -->

<!DOCTYPE tablefilter [
    <!ELEMENT tablefilter (database+)>
    <!ELEMENT database (catalog|schema)*>
    <!ATTLIST database type CDATA #REQUIRED>
    <!ELEMENT catalog (#PCDATA)>
    <!ELEMENT schema (#PCDATA)>
]>

<tablefilter>
    <!-- ODBC -->
    <database type="0">
    </database>
    
    <!-- Oracle -->
    <database type="1">
        <schema>APPQOSSYS</schema>
        <schema>AUDSYS</schema>
        <schema>AURORA$JIS$UTILITY$</schema>
        <schema>AURORA$ORB$UNAUTHENTICATED</schema>
        <schema>CTXSYS</schema>
        <schema>DBSNMP</schema>
        <schema>DIP</schema>
        <schema>DVF</schema>
        <schema>DVSYS</schema>
        <schema>GSMADMIN_INTERNAL</schema>
        <schema>GSMCATUSER</schema>
        <schema>GSMUSER</schema>
        <schema>LBACSYS</schema>
        <schema>MDSYS</schema>
        <schema>OJVMSYS</schema>
        <schema>OLAPSYS</schema>
        <schema>ORDDATA</schema>
        <schema>ORDPLUGINS</schema>
        <schema>ORDSYS</schema>
        <schema>OSE$HTTP$ADMIN</schema>
        <schema>OUTLN</schema>
        <schema>SI_INFORMTN_SCHEMA</schema>
        <schema>SPATIAL_CSW_ADMIN_USR</schema>
        <schema>SPATIAL_WFS_ADMIN_USR</schema>
        <schema>SYS</schema>
        <schema>SYSTEM</schema>
        <schema>WMSYS</schema>
        <schema>XDB</schema>
        <!-- APEX_xxxxxx and FLOWS_xxxxxx are versioned Oracle Application Express schemas -->
        <schema>APEX_*</schema>
        <schema>FLOWS_*</schema>
    </database>
    
    <!-- Sybase -->
    <database type="2">
        <schema>INFORMATION_SCHEMA</schema>
        <schema>sys</schema>
    </database>
    
    <!-- Informix -->
    <database type="3">
        <catalog>sysmaster</catalog>
        <schema>informix</schema>
        <schema>sysadmin</schema>
        <schema>syscdr</schema>
        <schema>sysutils</schema>
        <schema>sysuser</schema>
    </database>
    
    <!-- DB2 -->
    <database type="4">
        <schema>NULLID</schema>
        <schema>SQLJ</schema>
        <schema>SYSCAT</schema>
        <schema>SYSFUN</schema>
        <schema>SYSIBM</schema>
        <schema>SYSIBMADM</schema>
        <schema>SYSPROC</schema>
        <schema>SYSSTAT</schema>
        <schema>SYSTOOLS</schema>
    </database>
    
    <!-- MySQL -->
    <database type="5">
        <catalog>mysql</catalog>
        <schema>information_schema</schema>
        <schema>performance_schema</schema>
        <schema>sys</schema>
    </database>
    
    <!-- MS Access -->
    <database type="6">
    </database>

    <!-- Cloudscape / Derby -->
    <database type="9">
        <schema>INFORMATION_SCHEMA</schema>
        <schema>SYS</schema>
    </database>
    
    <!-- MS SQL Server -->
    <database type="7">
        <catalog>master</catalog>
        <catalog>model</catalog>
        <catalog>msdb</catalog>
        <catalog>tempdb</catalog>
        <schema>sys</schema>
        <schema>INFORMATION_SCHEMA</schema>
    </database>

    <!-- PostgreSQL -->
    <database type="11">
        <schema>information_schema</schema>
        <schema>pg_catalog</schema>
        <schema>pg_toast</schema>
        <schema>pg_toast_temp_*</schema>
        <schema>pg_temp_*</schema>
    </database>

    <!-- ClickHouse -->
    <database type="20">
        <catalog>system</catalog>
    </database>
</tablefilter>

